# Generated by Django 5.2.5 on 2025-09-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ro_code',
            field=models.CharField(blank=True, default='000100', max_length=255, null=True),
        ),
    ]
