# Generated by Django 5.2.5 on 2025-08-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('designation', models.CharField(choices=[('admin_officer', 'Administrative Officer'), ('assistant_manager', 'Assistant Manager')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.IntegerField(unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_designation', models.CharField(blank=True, choices=[('admin_officer', 'Administrative Officer'), ('assistant_manager', 'Assistant Manager')], max_length=100, null=True)),
                ('office_code', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('office_name', models.CharField(max_length=100, null=True)),
                ('housing_loan', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Whether housing loan was availed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_name', models.CharField(max_length=100)),
                ('landlord_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_details', models.FileField(blank=True, null=True, upload_to='bank_account_details')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_lease', models.CharField(choices=[('company', 'Company lease'), ('personal', 'Personal lease'), ('joint', 'Joint lease')], max_length=100)),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('lease_deposit', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('remarks', models.TextField(null=True)),
                ('status', models.CharField(default='pending', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
                ('joint_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_leases', to='lease_application.employee')),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord', to='lease_application.landlord')),
                ('primary_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_leases', to='lease_application.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('current_status', models.CharField(choices=[('paid', 'Paid to landlord'), ('received', 'Deposit received from landlord')], default='paid', max_length=100)),
                ('utr_number', models.CharField(max_length=100)),
                ('date_of_payment', models.DateField()),
                ('mode_of_refund', models.CharField(blank=True, choices=[('cheque', 'Cheque'), ('cash', 'Cash'), ('neft', 'NEFT')], max_length=100, null=True)),
                ('refund_instrument_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTR number / Cheque number')),
                ('date_of_refund', models.DateField(blank=True, null=True)),
                ('refund_payment_document', models.FileField(blank=True, null=True, upload_to='')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField()),
                ('lease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lease_application.leaseapplication')),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('rent_start_date', models.DateField(null=True)),
                ('rent_end_date', models.DateField(null=True)),
                ('payee_name', models.CharField(max_length=100)),
                ('payee_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payee_ifsc', models.CharField(blank=True, max_length=100, null=True)),
                ('payee_type', models.CharField(choices=[('landlord', 'Landlord'), ('employee', 'Employee')], max_length=20)),
                ('date_of_payment', models.DateField(null=True)),
                ('utr_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField()),
                ('lease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lease_application.leaseapplication')),
            ],
        ),
    ]
