# Generated by Django 5.2.5 on 2025-08-10 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deposit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_deposit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_eligibility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_eligibility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_landlord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_landlord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaseapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lease', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaseapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lease', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rent_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rent_payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
