# Generated by Django 5.2.5 on 2025-09-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_application', '0002_alter_deposit_created_by_alter_deposit_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='employee_deposit_share',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='employee_deposit_share_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='employee_deposit_share_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='employee_deposit_share_documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='deposit',
            name='employee_deposit_share_utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='general_poa',
            field=models.BooleanField(blank=True, null=True, verbose_name='Whether General power of attorney is available'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='landlord_mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='landlord_residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='legal_heir',
            field=models.BooleanField(blank=True, null=True, verbose_name='Whether legal heir'),
        ),
        migrations.AddField(
            model_name='leaseapplication',
            name='address_of_property',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='leaseapplication',
            name='carpet_area',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaseapplication',
            name='date_of_occupation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leaseapplication',
            name='date_of_termination',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='designation',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('senior_assistant', 'Senior Assistant'), ('admin_officer', 'Administrative Officer'), ('assistant_manager', 'Assistant Manager'), ('deputy_manager', 'Deputy Manager'), ('manager', 'Manager'), ('chief_manager', 'Chief Manager'), ('deputy_general_manager', 'Deputy General Manager'), ('general_manager', 'General Manager'), ('executive_director', 'Executive Director'), ('cmd', 'CMD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_designation',
            field=models.CharField(blank=True, choices=[('assistant', 'Assistant'), ('senior_assistant', 'Senior Assistant'), ('admin_officer', 'Administrative Officer'), ('assistant_manager', 'Assistant Manager'), ('deputy_manager', 'Deputy Manager'), ('manager', 'Manager'), ('chief_manager', 'Chief Manager'), ('deputy_general_manager', 'Deputy General Manager'), ('general_manager', 'General Manager'), ('executive_director', 'Executive Director'), ('cmd', 'CMD')], max_length=100, null=True),
        ),
    ]
