# Generated by Django 5.2.5 on 2025-09-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_application', '0003_deposit_employee_deposit_share_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseapplication',
            name='date_of_occupation',
        ),
        migrations.AddField(
            model_name='employee',
            name='housing_loan_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='landlord_email_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='general_poa',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Whether General power of attorney is available'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='legal_heir',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Whether legal heir'),
        ),
        migrations.AlterField(
            model_name='leaseapplication',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
